export const WIPE_STATE = 'WIPE_STATE';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const END_OF_PRODUCTS = 'END_OF_PRODUCTS';
export const RESET_PRODUCTS = 'RESET_PRODUCTS';

export const FETCH_AD_REQUEST = 'FETCH_AD_REQUEST';
export const FETCH_AD_SUCCESS = 'FETCH_AD_SUCCESS';
export const FETCH_AD_FAILED = 'FETCH_AD_FAILED';

export const PRELOAD_ITEMS = 'PRELOAD_ITEMS';
export const LOAD_ITEMS = 'LOAD_ITEMS';

export const SET_SORT = 'SET_SORT';
export const LOAD_BATCH = 'LOAD_BATCH';
